site_name: SmartNetLab # 左上角标题
site_url: https://SmartLab.github.io

theme:
  name: material
  palette: 
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
## [bottom-left corner]
copyright: Copyright &copy; 2022 HENU NETWORK LAB # 左下角的版权声明
## [bottom-right corner]

#以下是目录设置
nav:
  - SmartNetLab:
    - index.md
  - 区块链:
    - BlockChain/index.md
    - 区块链与机器学习:
      - 区块链与机器学习1: BlockChain/ML/ML1.md
      - 区块链与机器学习2: BlockChain/ML/ML2.md
    - 区块链与联邦学习: 
      - 区块链与联邦学习1: BlockChain/FL/FL1.md
      - 区块链与联邦学习2: BlockChain/FL/FL2.md
  - 网络流量识别: 
    - NetworkTrafficIdentification/index.md
    - 流量识别与机器学习:
      - 流量识别与机器学习1: NetworkTrafficIdentification/ML/ML1.md
      - 流量识别与机器学习2: NetworkTrafficIdentification/ML/ML2.md
    - 流量识别与联邦学习: 
      - 流量识别与联邦学习1: NetworkTrafficIdentification/FL/FL1.md
      - 流量识别与联邦学习2: NetworkTrafficIdentification/FL/FL2.md
  - 网络资源优化: 
    - NetworkAnomalyDetection/index.md
    - 网络资源优化与机器学习:
      - 网络资源优化与机器学习1: NetworkAnomalyDetection/ML/ML1.md
      - 网络资源优化与机器学习2: NetworkAnomalyDetection/ML/ML2.md
    - 网络资源优化与联邦学习: 
      - 网络资源优化与联邦学习1: NetworkAnomalyDetection/FL/FL1.md
      - 网络资源优化与联邦学习2: NetworkAnomalyDetection/FL/FL2.md
  - 网络资源优化: 
    - NetworkResourceOptimization/index.md
    - 网络资源优化与机器学习:
      - 网络资源优化与机器学习1: NetworkResourceOptimization/ML/ML1.md
      - 网络资源优化与机器学习2: NetworkResourceOptimization/ML/ML2.md
    - 网络资源优化与联邦学习: 
      - 网络资源优化与联邦学习1: NetworkResourceOptimization/FL/FL1.md
      - 网络资源优化与联邦学习2: NetworkResourceOptimization/FL/FL2.md